### ISSUE TITLE
lines dissappear when they go beyond the edges of the screen

### ISSUE THREAD

**Issue by gamedude-7** [gamedude-7/GameEngine#1]
maybe do a line intersection to the edge of the screen and draw the from start point to the intersection point

**Comment by joshi1983** [comment]
I'd like to take this issue on but I'm having some trouble getting the project to open in Visual Studio 2012.  Should I be opening with Visual Studio 2010 instead?

The following image shows the message I get.
![image](https://cloud.githubusercontent.com/assets/11838191/17422136/24e9c0b2-5a7d-11e6-931b-00868b44cfc8.png)

**Comment by gamedude-7** [comment]
I've already fixed this issue, and yeah, should be using vs 2010 instead

**Comment by joshi1983** [comment]
Cool
